<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html >
<head>
<meta charset="UTF-8">
<title>EXEMPLE JOINTURE SPRING </title>
<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="css/style.css?sinc=${sinc }" />
</head>
<body>
<h2>EXEMPLE JOINTURE SPRING</h2>
<div class="col-xs-6">
<table class="table table-striped">
    <caption></caption>
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">NAME</th>
            <th scope="col">EMAIL</th>
            <th scope="col">CITY</th>
        </tr>
    </thead>
    <tbody>
    <c:forEach var="p" items="${pers}">        
        <tr>
            <td>${p.idPers}</td>
            <td>${p.name}</td>
            <td>${p.email}</td>
            <td>${p.city.design}</td>
        </tr>
        </c:forEach>
    </tbody>
</table>
</div>
<figure  class="col-xs-offset-1 col-xs-4">
<img alt="mysql" src="img/mysql.png" />
<figcaption>Display in mysql</figcaption>
</figure>

<ul class="col-xs-offset-1 col-xs-10">
<h5>WEB-SERVICES</h5>
<li> <a href="http://localhost:1500/persons"> <strong>persons:</strong>generated by: com.example.demo.dao.PersonRepository</a>
<li> <a href="http://localhost:1500/cities"><strong>citys:</strong>generated by: com.example.demo.dao.CityRepository</a>
<li> <a href="http://localhost:1500/pers"><strong>person-join-city:</strong>generated by: com.example.demo.service.Join</a>
</ul>
</body>
</html>